"""add provider availability table

Revision ID: 0efee8744c19
Revises: b45a391322f2
Create Date: 2026-09-28 20:25:41.638979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '0efee8744c19'
down_revision: Union[str, Sequence[str], None] = 'b45a391322f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_availability',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_profile_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Enum('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', name='dayofweek'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_time > start_time', name='availability_end_after_start'),
    sa.ForeignKeyConstraint(['provider_profile_id'], ['provider_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('provider_availability')
    # create_table doesn't drop its enum types on downgrade — without
    # this, re-running upgrade() after a downgrade fails with "type
    # dayofweek already exists" (same gotcha as bookingstatus/mediatype).
    postgresql.ENUM(name='dayofweek').drop(op.get_bind(), checkfirst=True)
