"""add messages table

Revision ID: 2245f79fd675
Revises: 0efee8744c19
Create Date: 2026-09-29 20:07:57.980455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2245f79fd675'
down_revision: Union[str, Sequence[str], None] = '0efee8744c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # messages is a brand-new (empty) table, so a plain CREATE INDEX is
    # fine here — no concurrent-write risk to worry about yet. Indexes
    # added to tables that already exist elsewhere (bookings, reviews,
    # etc.) are split into 3b1f6c9d0aa1_add_indexes_for_scale.py instead,
    # using CREATE INDEX CONCURRENTLY since those tables may hold real
    # rows by the time this runs against a production database.
    op.create_index('ix_messages_booking_id_created_at', 'messages', ['booking_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_messages_booking_id_created_at', table_name='messages')
    op.drop_table('messages')
