"""add per-account login lockout fields

Revision ID: 566c8948a863
Revises: 26b2efe5b31c
Create Date: 2026-10-09 22:47:24.247577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '566c8948a863'
down_revision: Union[str, Sequence[str], None] = '26b2efe5b31c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('login_locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'login_locked_until')
    op.drop_column('users', 'failed_login_attempts')
    # ### end Alembic commands ###
