"""add bookings table

Revision ID: 9c2fe37b4c5d
Revises: d1a56813a16e
Create Date: 2026-09-15 21:58:39.574828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '9c2fe37b4c5d'
down_revision: Union[str, Sequence[str], None] = 'd1a56813a16e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # create_type=False on 'category': the 'servicecategory' Postgres enum
    # type already exists (created by provider_profiles' categories column
    # in an earlier migration) — without this, create_table tries to
    # CREATE TYPE again and fails with "type servicecategory already exists".
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('provider_profile_id', sa.UUID(), nullable=False),
    sa.Column('category', postgresql.ENUM('hair', 'makeup', 'nails', 'barber', 'skincare', name='servicecategory', create_type=False), nullable=False),
    sa.Column('visit_type', sa.Enum('shop_visit', 'house_call', name='visittype'), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('transport_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('requested', 'confirmed', 'completed', 'cancelled', name='bookingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['provider_profile_id'], ['provider_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('bookings')
    # Only drop the enum types this migration created (visittype,
    # bookingstatus) — 'servicecategory' is shared with provider_profiles
    # and must stay.
    postgresql.ENUM(name='visittype').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='bookingstatus').drop(op.get_bind(), checkfirst=True)
