"""add portfolio media table

Revision ID: cbc375651aa2
Revises: e5065ad5d68e
Create Date: 2026-09-21 20:44:44.429288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'cbc375651aa2'
down_revision: Union[str, Sequence[str], None] = 'e5065ad5d68e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_profile_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.Enum('photo', 'video', name='mediatype'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_profile_id'], ['provider_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('portfolio_media')
    # create_table doesn't drop its enum types automatically on downgrade —
    # without this, re-running upgrade() after a downgrade fails with
    # "type mediatype already exists" (same gotcha as bookingstatus/visittype
    # in 9c2fe37b4c5d_add_bookings_table.py).
    postgresql.ENUM(name='mediatype').drop(op.get_bind(), checkfirst=True)
