"""add audit log table

Revision ID: cd64d7aa8754
Revises: 369251391561
Create Date: 2026-10-10 14:46:18.909568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd64d7aa8754'
down_revision: Union[str, Sequence[str], None] = '369251391561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('verification_reviewed', 'report_reviewed', 'user_status_changed', 'provider_status_changed', 'sessions_revoked', name='auditaction'), nullable=False),
    sa.Column('target_type', sa.Enum('user', 'provider_profile', 'identity_verification', 'report', 'platform', name='audittargettype'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_admin_id_created_at', 'audit_logs', ['admin_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_target_type_target_id_created_at', 'audit_logs', ['target_type', 'target_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_logs_target_type_target_id_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_admin_id_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
