"""add categories to provider_profiles

Revision ID: d1a56813a16e
Revises: 76f631068005
Create Date: 2026-09-15 21:53:05.515207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1a56813a16e'
down_revision: Union[str, Sequence[str], None] = '76f631068005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


servicecategory_enum = postgresql.ENUM(
    'hair', 'makeup', 'nails', 'barber', 'skincare', name='servicecategory'
)


def upgrade() -> None:
    """Upgrade schema."""
    # Adjusted from the autogenerated version in two ways:
    # 1. Alembic's add_column doesn't create the Postgres ENUM type on its
    #    own the way create_table does — without this explicit create()
    #    first, the ALTER TABLE fails with "type servicecategory[] does
    #    not exist".
    # 2. Adding a NOT NULL column directly would fail against any DB that
    #    already has provider_profiles rows (there's no way to know what
    #    categories an existing provider actually offers). Add nullable,
    #    backfill to an empty array — a placeholder pending the provider
    #    updating their profile — then tighten to NOT NULL.
    servicecategory_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'provider_profiles',
        sa.Column('categories', postgresql.ARRAY(servicecategory_enum), nullable=True),
    )
    op.execute("UPDATE provider_profiles SET categories = '{}' WHERE categories IS NULL")
    op.alter_column('provider_profiles', 'categories', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('provider_profiles', 'categories')
    servicecategory_enum.drop(op.get_bind(), checkfirst=True)
