"""add phone number and notification preferences

Revision ID: f774f9f8bae1
Revises: 566c8948a863
Create Date: 2026-10-09 23:47:04.384477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f774f9f8bae1'
down_revision: Union[str, Sequence[str], None] = '566c8948a863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notify_on_new_message', sa.Boolean(), nullable=False),
    sa.Column('message_frequency', sa.Enum('every_message', 'first_message_only', name='messagenotificationfrequency'), nullable=False),
    sa.Column('notify_on_booking_status_change', sa.Boolean(), nullable=False),
    sa.Column('notify_on_new_review', sa.Boolean(), nullable=False),
    sa.Column('notify_on_verification_decision', sa.Boolean(), nullable=False),
    sa.Column('notify_on_report_decision', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
